from django.conf.urls import patterns, include, url

urlpatterns = patterns('alumnos.views',
	url(r'^$', 'index', name='index'),
	url(r'^actividad/(?P<id>[\w-]+)/$', 'actividad', name='actividad'),
	url(r'^asignar-actividad/$', 'asignar_actividad', name='asignar_actividad'),
	url(r'^asignar-catedra/$', 'asignar_catedra', name='asignar_catedra'),
	url(r'^asignar-clase-individual/$', 'asignar_clase_individual', name='asignar_clase_individual'),
	url(r'^asignar-talla/$', 'asignar_talla', name='asignar_talla'),
	url(r'^asignar/$', 'asignar', name='asignar'),
	url(r'^buscar-asignar-alumno/(?P<id>[\w-]+)$', 'buscar_asignar_alumno', name='buscar_asignar_alumno'),
	url(r'^buscar-editar-alumno/(?P<id>[\w-]+)$', 'buscar_editar_alumno', name='buscar_editar_alumno'),
	url(r'^buscar-horario/(?P<id>[\w-]+)$', 'buscar_horario', name='buscar_horario'),
	url(r'^buscar-visualizar-alumno/(?P<id>[\w-]+)$', 'buscar_visualizar_alumno', name='buscar_visualizar_alumno'),
	url(r'^catedra/(?P<id>[\w-]+)/$', 'catedra', name='catedra'),
	url(r'^editar/$', 'editar', name='editar'),
	url(r'^guardar-actividad/$', 'guardar_actividad', name='guardar_actividad'),
	url(r'^guardar-clase/$', 'guardar_clase', name='guardar_clase'),
	url(r'^guardar-datos/$', 'guardar_datos', name='guardar_datos'),
	url(r'^guardar-individual/$', 'guardar_individual', name='guardar_individual'),
	url(r'^guardar-prenda/$', 'guardar_prenda', name='guardar_prenda'),
	url(r'^individual/(?P<id>[\w-]+)/$', 'individual', name='individual'),
	url(r'^rastrear-alumno/$', 'rastrear_alumno', name='rastrear_alumno'),
	url(r'^registrar-alumno/$', 'registrar_alumno', name='registrar_alumno'),
	url(r'^registrar/$', 'registrar', name='registrar'),
	url(r'^tallas/(?P<id>[\w-]+)/$', 'tallas', name='tallas'),
	url(r'^visualizar/$', 'visualizar', name='visualizar'),

)